### ISSUE TITLE
请问能不能给一份数据集？

### ISSUE THREAD

**Issue by Daydaylight** [reresearcher/DAEH#1]
您好： 
感谢您公布code。
我从别的论文中下载的格式和数据的划分与您代码中的不太一致，能不能给我一份数据集以让我更好的复现您这篇论文？
期待您的回复！

**Comment by reresearcher** [comment]
好嘞，不过等等学生哈，目前在准备预答辩，人快无了

**Comment by reresearcher** [comment]
> > 
> 
> 谢谢学长，我不急。
抱歉久等了，以下是我整理的数据集文件。
链接：https://pan.baidu.com/s/1xNN6fqUS_uAvjSXAPcxRyA 
提取码：AAAA

**Comment by Daydaylight** [comment]
十分感谢您
